# Uncomment the next line to define a global platform for your project
 platform :ios, '13'

target 'CanadaInfo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CanadaInfo
  pod 'Alamofire', '5.1.0'
  pod 'AlamofireImage', '4.1'
end
